# Generated by Django 5.0.4 on 2024-05-07 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_address_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.AddField(
            model_name='event',
            name='created_by_venue_manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.venuemanager'),
            preserve_default=False,
        ),
    ]
