# Generated by Django 5.0.4 on 2024-05-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image_url',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='default.png', upload_to='event_images/'),
            preserve_default=False,
        ),
    ]
