# Generated by Django 5.0.4 on 2024-05-18 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
