# Generated by Django 5.0.4 on 2024-05-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_delete_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemanager',
            name='role',
            field=models.CharField(default='STAFF', max_length=50),
            preserve_default=False,
        ),
    ]
