# Generated by Django 5.0.4 on 2024-05-29 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticketorder_ticket_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='order_id',
            new_name='order_num',
        ),
    ]
