# Generated by Django 5.0.4 on 2024-05-30 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_order_id_ticket_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
