# Generated by Django 5.0.4 on 2024-06-02 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_order_num_ticket_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='last_name',
        ),
    ]
