# Generated by Django 5.0.4 on 2024-06-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticketorder_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='order_total',
        ),
    ]
