# Generated by Django 5.0.4 on 2024-06-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_ticketorder_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='payment_intent',
            field=models.CharField(max_length=64),
        ),
    ]
